experiment:
  name: baseline

paths:
  input_loc:  /kaggle/input/competitions/aisehack-theme-2/test_in/
  checkpoint: /kaggle/working/experiments/baseline/checkpoints/fno_baseline_ep99.pt
  output_loc: /kaggle/working/
  norm_stats: /kaggle/working/norm_stats.npy   # replaces min_max_file

data:
  ntest:      996
  time_input: 10
  time_out:   16
  S1:         140
  S2:         124

features:
  met_variables:      ['cpm25', 'pblh', 'rain', 'u10', 'v10']
  emission_variables: ['PM25', 'NH3', 'SO2', 'NOx', 'NMVOC_combined']

model:
  modes: 8
  width: 24
