paths:
  raw_path:      /kaggle/input/competitions/aisehack-theme-2/raw
  train_savepath: /kaggle/temp/data/train/
  val_savepath:   /kaggle/temp/data/val/

data:
  months:   ['APRIL_16', 'JULY_16', 'OCT_16', 'DEC_16']
  horizon:  26
  stride:   3       # was 1, reduces dataset from ~64GB to ~21GB
  val_frac: 0.2
  seed:     0

features:
  met_variables_raw:      ['cpm25', 'pblh', 'rain', 'u10', 'v10']
  emission_variables_raw: ['PM25', 'NH3', 'SO2', 'NOx', 'NMVOC_e', 'NMVOC_finn']
