experiment:
  name: baseline

paths:
  savepath_train: /kaggle/temp/data/train/
  savepath_val:   /kaggle/temp/data/val/
  model_save_path: /kaggle/working/experiments/baseline/checkpoints/fno_baseline.pt
  save_dir:        /kaggle/working/experiments/baseline/logs/log.json

data:
  time_input: 10
  time_out:   16
  S1: 140
  S2: 124

features:
  met_variables:      ['cpm25', 'pblh', 'rain', 'u10', 'v10']
  emission_variables: ['PM25', 'NH3', 'SO2', 'NOx', 'NMVOC_combined']

model:
  modes: 8   # reduced from 12
  width: 24  # reduced from 32

training:
  batch_size:       4
  epochs:           100
  lr:               1e-3
  weight_decay:     1e-4
  scheduler_step:   50
  scheduler_gamma:  0.5
  checkpoint_every: 10
